name: Build and Deploy Nginx Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-argocd-deployment-image:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Nginx container to server
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-argocd-deployment-image:${{ github.run_id }}
            docker stop nginx-container || true
            docker rm nginx-container || true
            docker run -d --name nginx-container -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-argocd-deployment-image:${{ github.run_id }}
          EOF

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]  # Ensure this job runs after both build and deploy jobs
    if: always()  # Run this job regardless of the outcome of other jobs

    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # SMTP server for Gmail
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GitHub Actions CI/CD Pipeline - ${{ github.workflow }} - ${{ job.status }}
          to: ${{ secrets.EMAIL }}
          from: GitHub Actions <${{ secrets.EMAIL }}>
          body: |
            CI/CD Pipeline Summary for ${{ github.repository }}:

            Build Status: ${{ needs.build.result }}
            Docker Build & Push Status: ${{ needs.build.result }}
            Deploy Status: ${{ needs.deploy.result }}
