name: Build, Push Docker Image, and Send Notification

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:${{ github.run_id }}

  notify:
  runs-on: ubuntu-latest
  needs: build
  if: success()  # Only run this job if the previous job was successful
  steps:
    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # Change this to your SMTP server
        server_port: 465
        username: ${{ secrets.EMAIL }}  # Your email
        password: ${{ secrets.SMTP_PASSWORD }}  # Your SMTP password
        subject: GitHub Actions CI/CD Pipeline - Build and Push Success
        from: GitHub Actions <${{ secrets.EMAIL }}>
        to: ${{ secrets.NOTIFY_EMAIL }}  
        body: |
          CI/CD Pipeline Summary for ${{ github.repository }}:

          Build and Push Status: Success

          Docker Image Tag: ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:${{ github.run_id }}

          For more details, check the [GitHub Actions log](${{
            github.server_url
          }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
